baseURL = "http://fat-dragon.org/"
languageCode = "en-us"
title = "The Fat Dragon"
theme = "base16"
pygmentsuseclasses = true
pygmentsUseClassic=true
PygmentsCodeFences=true

[blackfriday]
fractions = false
